% -------------------------------------------------------------------
%  Generated by MATLAB on 5-May-2026 14:14:12
%  MATLAB version: 24.2.0.2923080 (R2024b) Update 6
% -------------------------------------------------------------------
                                                           

AH = 217;

AH1 = 108.5;

Cable_Temp = 25;

R0 = 0.02;

R0_T2 = 0.05;

R_RC1 = 0.005;

R_RC1_T2 = 0.0125;

R_RC2 = 0.01;

R_RC2_T2 = 0.025;

R_SD = 1.0E+6;

SOC0 = 0.7;

Sig = Simulink.Signal;
Sig.CoderInfo.StorageClass = 'Auto';
Sig.Description = '';
Sig.DataType = 'auto';
Sig.Min = [];
Sig.Max = [];
Sig.DocUnits = '';
Sig.Dimensions = -1;
Sig.DimensionsMode = 'auto';
Sig.Complexity = 'auto';
Sig.SampleTime = -1;
Sig.InitialValue = '';

T1 = 25;

T2 = 0;

V1 = 357;

V1_T2 = 352;

Vnom = 403.2;

Vnom_T2 = 400;

tau1 = 30;

tau1_T2 = 60;

tau2 = 300;

tau2_T2 = 600;

